### ISSUE TITLE
Enhance the satisfaction information in the budget screen

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-player#41]
The satisfaction information is pretty bare, and can be enhanced with more information.

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/92b5aa1e-bfcf-49fc-9a8e-0afe57d2e3fe)

In this case, the player lost a point to buying a house with a lower satisfaction. This is not displayed. Also, loss of satisfaction to debt is not shown. This can be improved.

**Comment by vjcortesa** [comment]
Here is the summary overview, with all the information. However, it becomes too long when including all the fields. Would it be better not to include the ones that have a zero value?
![240224_Adjust the satisfaction overview in the last screen](https://github.com/averbraeck/housinggame-player/assets/8215750/cc6f4c79-8f63-420c-ab5c-532356f2e8bd)

**Comment by averbraeck** [comment]
This is what it looks like now:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/72734c7e-3d1d-4368-8f44-0b3eac29ced6)

**Comment by averbraeck** [comment]
Or for someone who bought a lot of measures:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/60c7e710-0f36-448a-adcf-1d1435179bd7)

(the measures bought were indeed 7 satisfaction points:)
![image](https://github.com/averbraeck/housinggame-player/assets/13779793/0913dfb4-532b-4d2f-aec6-0fadc0cfd8c1)

**Comment by averbraeck** [comment]
Done and tested for a number of users in different stages of the game.
