### ISSUE TITLE
read-budget screen should be updated earlier with bought/sold house, taxes, etc.

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-player#42]
The read-budget screen in higher rounds does not show the complete picture for the budget:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/bbf798f0-df38-4ba3-8c9e-387f17d90160)

As a result, the numbers don't add up to the spendable income.

**Comment by averbraeck** [comment]
Calculation could be shown earlier. The end calculation does seem to completely correct, however:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/99750460-10e4-43de-a81c-022eca5e7fb7)

**Comment by averbraeck** [comment]
But there are also cases where the end information is very incomplete:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/dba546f3-771d-4f0c-aa2a-6cf8f2ca920e)

What is missing here is:
- mortgage payment: 20k
- taxes: 20k
- bought measures: 20k

If these would be shown, the overview would be correct.

**Comment by vjcortesa** [comment]
@averbraeck In IHE Delft, the overview in higher rounds at the end was not showing all the categories
![240406_t2p5_spendable income error](https://github.com/averbraeck/housinggame-player/assets/8215750/60c25fa9-0740-4f7e-87d3-5aea428be647)

**Comment by averbraeck** [comment]
The full information is now shown, and partial information is also shown earlier:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/1c7a65c1-fbb7-4150-83a5-37e0164ad26c)

And this is the screen right after buying a house:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/8bd26c3e-897c-4a04-85a2-038584d4494f)

**Comment by averbraeck** [comment]
This issue seems solved.
