### ISSUE TITLE
Protection levels in player's flood accordion wrong

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-player#45]
They seem to be added per round (or are just too high). See:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/4a293a6c-0938-4752-963f-c791df58bb01)

**Comment by averbraeck** [comment]
Another example that also shows that the calculated numbers at the top are different from the ones in the table (ans also very wrong):

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/261e5efe-1174-4ccf-ae31-fa85aabafb57)

**Comment by averbraeck** [comment]
The correct numbers for player t6p1 from the example above should be for round 2:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/33ba009b-0062-484f-b2cb-44fc53124209)

House protection of 13 for rain and 15 for river. For round 1 it should be 6 for rain and 10 for river for the house protection (same as community, no extra measures).

**Comment by vjcortesa** [comment]
The game bug repeats itself 
![240204_Game play of Thomas](https://github.com/averbraeck/housinggame-player/assets/8215750/929c5a6b-0283-4b33-8c8c-7db4e04b9f7a)
![240224_Round 1 overview](https://github.com/averbraeck/housinggame-player/assets/8215750/49d3008a-56d0-47d2-bfac-fb378f63e659)

**Comment by vjcortesa** [comment]
- [ ] Align the facilitator and player order to show the rain first and then the river information
- [ ] Dices give flood level not intensity
- [ ] Abbreviations were confusing for players so better to write the full word with line break <br/>
![240224_Show damage screen](https://github.com/averbraeck/housinggame-player/assets/8215750/47d163ee-c06d-4198-94b5-ddc0d6e4dd8e)

**Comment by averbraeck** [comment]
This has been repaired:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/2cab77e7-42da-42da-92dd-560fbe09369a)
![image](https://github.com/averbraeck/housinggame-player/assets/13779793/8532e0dd-41b7-4934-b280-d95db9bf1a2d)
