### ISSUE TITLE
Adapt screens to reflect game flow

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-player#5]
More information is available for the player in the `playerround` record. We have to select which information to display at the start of a new round, and how to structure and format this data.

**Comment by averbraeck** [comment]
The READ_BUDGET screen shows the data according to the new playerround structure. However, we might want to rethink what we exactly display here.

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/93e7fe86-3aef-4a15-8964-cd696b53046d)

**Comment by vjcortesa** [comment]
To improve readability and overview, I suggest headers to distinguish budget parts and expectations, gray boxes to distinguish instructions from updated calculations, and icons relating to the key game scores
![231201_New round_read budget](https://github.com/averbraeck/housinggame-player/assets/8215750/b795ff66-87fe-41ab-acda-296a4f9df42d)

The news follows the same layout (after all, we need a SHOW HOUSES/VIEW HOUSES state)
![231201_Round news_read news](https://github.com/averbraeck/housinggame-player/assets/8215750/4e1eada5-67ad-48b8-983b-2d093af104a9)

Finally, the screen for the player's state VIEW HOUSES
![231201_House market_house buying](https://github.com/averbraeck/housinggame-player/assets/8215750/0349c8ad-d7ae-43f3-a303-a6e54b1b3bd2)

**Comment by vjcortesa** [comment]
Based on the comments to the above, I will update these quick and dirty screens that we did today
![Uploading 231201_Player_House market_house buying_q&d.png…]()

**Comment by vjcortesa** [comment]
Move in and move out screens to confirm buying and sell
![231204_Player_House market_move in_move out](https://github.com/averbraeck/housinggame-player/assets/8215750/efb0b21c-b15f-4c9b-aa57-95aaef1c30a6)

**Comment by vjcortesa** [comment]
I don't know if I will repeat all the house information. Yet, on the top, I put the taxes to pay, an estimation because the facilitator will deduct the actual value after all buying requests are approved.
![231204_Player_House market_pay taxes](https://github.com/averbraeck/housinggame-player/assets/8215750/dc88a5fd-76e7-480a-b390-a70c78e31d21)

**Comment by vjcortesa** [comment]
![231208_Player_Buy improvements with flood information](https://github.com/averbraeck/housinggame-player/assets/8215750/67e08efd-97d4-467f-b26c-8da43b2f5bc3)

**Comment by vjcortesa** [comment]
![231209_Player_answer survey](https://github.com/averbraeck/housinggame-player/assets/8215750/e3e5ce40-8991-4dd7-9ee7-05222abed9e4)

**Comment by vjcortesa** [comment]
![231210_Player_6- View damage with   without info](https://github.com/averbraeck/housinggame-player/assets/8215750/4e1550d2-672d-4129-ae38-6805a66bd71f)

**Comment by averbraeck** [comment]
All initial screens have been created and work. Enhancements and bugs are shown in other issues.
