### ISSUE TITLE
Improve clarity of 1. Your budget and expectations screen

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#51]
- [ ] **It is unclear to the players what values are constant every round:** The facilitator can explain that aspect by adding an * to the applicable values and a note below.
![240224_Adjustments for clarity to the budget and expectations](https://github.com/averbraeck/housinggame-player/assets/8215750/40bcf062-abc5-40c8-beed-88bed4e031d1)

**Comment by averbraeck** [comment]
I do not think it is wise to hard-code this. Future versions of the game could have changes in these values as a result of news measures (e.g., increased living costs). Therefore, I would not like to change this. Also, the (*) gives extra clutter on the screen.
