### ISSUE TITLE
Player does not notice when the taxes are payed

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#52]
- [ ] the player does not notice when the taxes are paid, probably because it is not outlined with a header in the corresponding screen: Add a header about it, namely tax payment.
- [ ] What does the note below applies to is not clear: Shorten the text and indicate with an "*" to which category applies
- [ ] Missing article when mentioning the community: Add "the"?

![240224_Adjustments for clarity to your community taxes](https://github.com/averbraeck/housinggame-player/assets/8215750/ea0450f1-1858-43ed-9c8f-8bd4dd1fcfde)

**Comment by averbraeck** [comment]
Done 

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/49ea7e9b-540a-476d-91c5-aa97b47c3264)
