### ISSUE TITLE
Very low satisfaction values and a mysterious change of house

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#55]
- [ ] In the IHE Table, 1 some players ended up with very low satisfaction values, why was the case
- [ ] The player t1p3 had some mysterious house exchange ended up living in the N04 house but thought was living in the D04 house. Options that we consider for that mystery are: 
- [ ] The facilitator did not give the player the right house sheet or check that the player put the pawn at the right location. 
- [ ] The player had the intention to move out in earlier rounds, and send the move out request after the facilitator closed the selling. Although is possible to do so, weird errors appear 

![240224_Very low satisfaction values make doubt](https://github.com/averbraeck/housinggame-player/assets/8215750/72939f6f-3d22-4335-aa1d-cc5ac93d4f96)

**Comment by averbraeck** [comment]
Player t1p1
- start value: 5 satisfaction points
- round 1: 3 damage points for river, 2 damage points for rain. Total = 5
- round 2: 2 damage points for river,. Total = 2
- round 3: no damage
- round 4: 2 damage points for river. Total = 2.
- Flooding: total = -9 satisfaction points.
- Every round in debt = -5 points.
- House satisfaction when buying = -1 point.

This is in total 15 negative satisfaction points, so the end score should have been -10 and not -14.

This has to do with the wrong calculation of the flood damage that has now been repaired as part of one of the other issues. This should therefore be correct in the new version, but DO check!

**Comment by averbraeck** [comment]
Player t1p3 did indicate N04 and not D04 in round 1:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/ad588f24-effc-4d7b-9e2d-10c24dbb12ce)

Only in round 2, there was first a rejected_stay, and then an approved_stay, but not a buy of a new house. House D04 did not get a single transaction during the game, so it must have been a misplaced pawn.

**Comment by averbraeck** [comment]
Game seems consistent. But calculation of the satisfaction points should be carefully rechecked. See https://github.com/averbraeck/housinggame-player/issues/61.

**Comment by vjcortesa** [comment]
I found out how we arrive to the low satisfaction values, but the correct value should have been -13 and not -14
![image](https://github.com/averbraeck/housinggame-player/assets/8215750/6ce30bbc-f6d7-47d1-8256-2890683a7bf3)
River flooding: 
•	Damage: dice – protection (public + private): water volume you are unprotected for
•	Satisfaction: Damage (+ 1 if area flooded)
For example, you are unprotected if you have 2 damage due to the water volume. Therefore, one will get 3 satisfaction lost, equal to 1 for every damage plus the satisfaction penalty if the area is flooded
Rain flooding: 
•	Damage: If the dice number is higher than the protection of the area and the player does not have private protection against rain floods, the damage is 1, yes otherwise, 0, no. 
•	Satisfaction: same applies. There is no additional satisfaction penalty if the area is flooded.
