### ISSUE TITLE
Spendable income for a house using more than the savings

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#56]
- [ ] According to the initial rules of the game, the spendable income for buying a house was: savings + Max mortgage
- [ ] However, we are now allowing to use all money available on a house.
- [ ] An advantage is that players with lower incomes can afford more houses but without a reminder of not using all their money, players may also run out of money faster. 
![240224_Spendable income to buy a house](https://github.com/averbraeck/housinggame-player/assets/8215750/8d0bb387-59bf-4114-8a9c-540416694fca)

**Comment by averbraeck** [comment]
This is not a bug. The savings at any given moment are calculated as the available money at that moment (like in real life). Therefore, the savings do include the round income minus the living costs. I do not see how anything else could be logical. Of course, players should allow for upcoming costs, but the way it is calculated now, is totally consistent with the real world. The maximum mortgage, however, does NOT change based on the available money of the player -- this is dependent on the welfare level.

I do not see this as a bug, and it would be very illogical to change it from how it is implemented.
