### ISSUE TITLE
Improve clarity of Buy-house-wait

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#57]
- [ ] Text is not readable within the available time: Add headers to allow the player to quickly screen what is each text about
![240224_Adjust house choice](https://github.com/averbraeck/housinggame-player/assets/8215750/30517283-0a88-48d4-8dfe-8e156b6846af)

**Comment by averbraeck** [comment]
Done.

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/b6e31d80-e187-468d-8395-ec749652ac67)
