### ISSUE TITLE
Taxes are deducted twice and debt penalty not applied

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#58]
- [ ] When players move into the house and receive the house confirmation, taxes are already deducted in 1- budget and expectations, when it should be only until the taxes calculation
- [ ] The error only occurs when the facilitator allows buying a house by going in debt and when buying a house that it is affordable
- [ ] Whenever in debt (in this case because the facilitator approved to go in debt), the debt penalty is not applied in the satisfaction score.
![240224_Adjust house confirmation budget](https://github.com/averbraeck/housinggame-player/assets/8215750/89e85692-e618-4b08-9d36-414d7e686da4)
![240224_Taxes applied twice](https://github.com/averbraeck/housinggame-player/assets/8215750/6c1b4446-dcc7-4374-98eb-40bab5d57951)

**Comment by averbraeck** [comment]
I do not understand. Taxes have to be paid. The calculation is only made when the facilitator presses "show taxes", not before. 
The debt penalty is only paid at the START of a new round, not at any other point. 

Before pressing "show taxes", and after a player bought a house, the budget overview looks as follows:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/c3310864-3305-473e-aba4-0f577cb77eff)

This is correct, as far as I can see... No taxes yet.

**Comment by averbraeck** [comment]
I do not see anything wrong. All calculations seem correct, and are shown at the right time to the player.
