### ISSUE TITLE
Buying improvements screen: Making satisfaction measures more prominent and reducing flood adaptation measures

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#63]
We agreed to remove two adaptation measures:
- Raise the ground level, which is possible in the USA but somehow unrealistic or uncommon in NL.
- Steel water walls are not very distinguished from the bulkhead door flood barrier.
- Yet, to do on the administrator side, but possible without changing the code, is to align all measure names with the game material and find an alternative name.
We added two satisfaction measures that represent three options:
- Modest house renovations
- Structural house changes
- Personal Improvements
House renovations share the same card to avoid cluttering the player's table with too many options. Yet divided in three on the implementation screen

Yet to do it is to increase the house prices when housing innovation measures, but it is too risky for the September 26 testing, so we will postpone it for the next playing. Yet, we should keep in mind that game plays may increase if moving is encouraged. For now, it is wise to check the gameplay durations without encouraging it and later on compare.
![House Renovations](https://github.com/user-attachments/assets/21163af9-bfb7-448d-b3e0-62ac7d6a0915)

**Comment by averbraeck** [comment]
I like the idea that you can not buy unlimited satisfaction points, but that these are limited to a one-time-per-round buying of satisfaction. This will lead to a change in the database, program structure, and game logic, but it seems very do-able to implement this. I think it is a great improvement. 

When this is implemented, any number of house related or personal related improvements can be included in the game, and this can be further tweaked in terms of number of measures, type of measures, descriptions, and percentage of income that this takes. 

I will work this out in a number of changes
- common project: database changes in `scenarioparameters`, `measuretype` and `measure`; potentially more. 
- admin project: ability to set and change values for the database changes.
- admin project: ability to enter satisfaction-only measures.
- player project: screen changes for the measure screen; calculation changes.
- facilitator project: overview of the bought changes, including personal ones.

**Comment by averbraeck** [comment]
There are now **house measures** and **personal measures**. All measures belong to a **category**. In the example below, three categories are used:

![image](https://github.com/user-attachments/assets/012a4614-1b48-41a4-ae48-94b93c278621)

Noe that the texts in italic can be changed in the database:

![image](https://github.com/user-attachments/assets/78ad84bf-008b-41fb-9b73-a3249a2ca434)

**Comment by averbraeck** [comment]
All the required changes have been implemented.
