### ISSUE TITLE
Build BOUGHT_HOUSE screen

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-player#8]
The screen for the BOUGHT_HOUSE has not yet been created. A first implementation is needed.

**Comment by vjcortesa** [comment]
All player screens are referred to in this issue https://github.com/averbraeck/housinggame-player/issues/5 to see the game flow. Here, I placed only the bought / sold house screen for the first and second rounds so players can move in and move out accordingly.
![231204_Player_House market_move in_move out](https://github.com/averbraeck/housinggame-player/assets/8215750/a6499585-0878-44a7-b8b2-14feb6fe86f4)

**Comment by averbraeck** [comment]
Bought house screen shows the correct information:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/f11c818e-911d-4033-9d61-69e25a567474)
